# Generated by Django 4.1.3 on 2023-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApxbFleetMain', '0002_rename_name_driver_first_name_driver_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='driver',
            name='location_long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
