# Generated by Django 4.1.3 on 2023-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApxbFleetMain', '0003_remove_driver_location_lng_driver_location_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_pictures/'),
        ),
    ]
